root: true
parserOptions:
  parser: "@typescript-eslint/parser"
  project: "./packages/urql/tsconfig.json"
plugins:
  - "@typescript-eslint"
extends:
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - prettier
