root: true
env:
  browser: true
  es2022: true
  node: true
  vue/setup-compiler-macros: true
parserOptions:
  parser: "@typescript-eslint/parser"
  project: "tsconfig.json"
  extraFileExtensions: [".vue"]
plugins:
  - "@typescript-eslint"
  - vue
extends:
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:@typescript-eslint/recommended
  - plugin:vue/vue3-essential
  - plugin:vue/vue3-strongly-recommended
  - plugin:vue/vue3-recommended
  - plugin:prettier/recommended
  - prettier
rules:
  vue/block-lang:
    - error
    - script:
        lang: ts
  vue/block-tag-newline:
    - error
    - singleline: always
      multiline: always
      maxEmptyLines: 0
  vue/component-api-style: error
  vue/component-options-name-casing: error
  vue/custom-event-name-casing: error
  vue/define-macros-order: error
  vue/html-button-has-type: error
  vue/html-comment-content-newline: error
  vue/html-comment-content-spacing: error
  vue/html-comment-indent: error
  vue/match-component-file-name:
    - error
    - extensions: [".js", ".jsx", ".ts", ".tsx", ".vue"]
      shouldMatchCase: true
  vue/match-component-import-name: error
  vue/next-tick-style:
    - error
    - promise
  vue/no-boolean-default:
    - error
    - default-false
  vue/no-duplicate-attr-inheritance: error
  vue/no-empty-component-block: error
  vue/no-multiple-objects-in-class: error
  vue/no-potential-component-option-typo: error
  vue/no-template-target-blank: error
  vue/no-this-in-before-route-enter: error
  vue/no-undef-components: error
  vue/no-undef-properties: error
  vue/no-unsupported-features: error
  vue/no-unused-properties:
    - error
    - groups: ["props", "data", "computed", "methods", "setup"]
      deepData: true
  vue/no-unused-refs: error
  vue/no-useless-mustaches: error
  vue/no-useless-v-bind: error
  vue/no-v-text: error
  vue/prefer-prop-type-boolean-first: error
  vue/prefer-separate-static-class: error
  vue/prefer-true-attribute-shorthand: error
  vue/require-emit-validator: error
  vue/require-expose: error
  vue/require-name-property: error
  vue/script-indent: error
  vue/v-for-delimiter-style: error
  vue/v-on-function-call: error
  vue/array-bracket-newline: error
  vue/array-bracket-spacing: error
  vue/arrow-spacing: error
  vue/block-spacing: error
  vue/brace-style: error
  vue/camelcase: error
  vue/comma-dangle:
    - error
    - always-multiline
  vue/comma-spacing: error
  vue/comma-style: error
  vue/dot-location: error
  vue/dot-notation: error
  vue/eqeqeq: error
  vue/func-call-spacing: error
  vue/key-spacing: error
  vue/keyword-spacing: error
  vue/max-len:
    - error
    - code: 120
      comments: 120
      template: 120
      ignoreHTMLAttributeValues: true
      ignoreUrls: true
  vue/no-constant-condition: error
  vue/no-empty-pattern: error
  vue/no-extra-parens: off
  vue/no-irregular-whitespace: error
  vue/no-loss-of-precision: error
  vue/no-sparse-arrays: error
  vue/no-useless-concat: error
  vue/object-curly-newline: error
  vue/object-property-newline: error
  vue/object-shorthand: error
  vue/operator-linebreak: error
  vue/prefer-template: error
  vue/space-in-parens: error
  vue/space-infix-ops: error
  vue/space-unary-ops: error
  vue/template-curly-spacing: error
  # "@typescript-eslint/no-misused-promises":
  # - error
  # - checksVoidReturn:
  #     arguments: false
  #     attributes: false
overrides:
  - files: ["postcss.config.js", "quasar.config.js"]
    env:
      node: true
    rules:
      "@typescript-eslint/no-var-requires": off
