bracketSpacing: true
printWidth: 120
semi: true
singleAttributePerLine: true
singleQuote: false
tabWidth: 2
trailingComma: all
useTabs: false
overrides:
  - files: ["*.ts", "*.tsx"]
    options:
      parser: typescript
